/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beasiswa;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Kelas.koneksi;
import net.proteanit.sql.DbUtils;
import java.awt.FlowLayout;


/**
 *
 * @author RRQ'Toothless
 */
public class FData_Mahasiswa extends javax.swing.JFrame {
    ResultSet resultset;
    Statement statement;
    
    

    public FData_Mahasiswa() {
        initComponents();
        tombol(false);
        bersih();
        viewdata();        
    }
    public void viewdata(){
        Kelas.inputdata idn = new Kelas.inputdata();
        try{
            tabellist.setModel(DbUtils.resultSetToTableModel(idn.Updatelisttable()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    void filterangka(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Kolom Ini Hanya Bisa Memasukan Karakter Angka");
        }
    }
    void filterhuruf(KeyEvent b){
        if(Character.isDigit(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Kolom Ini Hanya Bisa Memasukan Karakter Huruf");
        }
    }
    void bersih(){
            txt_nim.setText("");
            txt_nama.setText("");
            cmb_jk.setSelectedIndex(0);
            txt_almt.setText("");
            txt_nama_pt.setText("");
            txt_prodi.setText("");
            txt_semester.setText("");
            txt_angkatan.setText("");
            txt_ipk.setText("");
            txt_prestasi.setText("");
            txt_no_hp_mhs.setText("");
            txt_kerja_ortu.setText("");
            txt_hasil_rata.setText("");
            txt_jumlah_tanggungan.setText("");
            txt_no_hp_ortu.setText("");
            txt_namabank.setText("");
            txt_norek.setText("");
            txt_status.setText("-");
    }
    void tombol(boolean status){
        btn_edit.setEnabled(status);
        btn_hapus.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_jk = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_almt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nama_pt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_prodi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_semester = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_angkatan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_ipk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_prestasi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_no_hp_ortu = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_kerja_ortu = new javax.swing.JTextField();
        btn_keluar = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_baru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellist = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txt_hasil_rata = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_jumlah_tanggungan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_namabank = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_norek = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_no_hp_mhs = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mahasiswa");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 10, 140, 29);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Form");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 10, 40, 17);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 1367, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 110, 21, 15);

        txt_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nimActionPerformed(evt);
            }
        });
        txt_nim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nimKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nim);
        txt_nim.setBounds(230, 100, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 150, 30, 15);

        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nama);
        txt_nama.setBounds(230, 140, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 71, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Mahasiswa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 70, 99, 15);

        cmb_jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Jenis Kelamin --", "PRIA", "WANITA" }));
        cmb_jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jkActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_jk);
        cmb_jk.setBounds(230, 180, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 230, 37, 15);

        txt_almt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_almt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_almtKeyTyped(evt);
            }
        });
        getContentPane().add(txt_almt);
        txt_almt.setBounds(230, 220, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Perguruan Tinggi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 110, 127, 15);

        txt_nama_pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_ptActionPerformed(evt);
            }
        });
        txt_nama_pt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nama_ptKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nama_pt);
        txt_nama_pt.setBounds(670, 100, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Program Studi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 150, 77, 15);

        txt_prodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prodiKeyTyped(evt);
            }
        });
        getContentPane().add(txt_prodi);
        txt_prodi.setBounds(670, 140, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 190, 52, 15);

        txt_semester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_semesterKeyTyped(evt);
            }
        });
        getContentPane().add(txt_semester);
        txt_semester.setBounds(670, 180, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Angkatan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 230, 52, 15);

        txt_angkatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_angkatanKeyTyped(evt);
            }
        });
        getContentPane().add(txt_angkatan);
        txt_angkatan.setBounds(670, 220, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IPK");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 270, 18, 15);

        txt_ipk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ipkKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ipk);
        txt_ipk.setBounds(670, 260, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Prestasi");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(970, 110, 41, 15);

        txt_prestasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prestasiKeyTyped(evt);
            }
        });
        getContentPane().add(txt_prestasi);
        txt_prestasi.setBounds(1100, 100, 180, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No HP");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(970, 150, 34, 15);

        txt_no_hp_ortu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_hp_ortuKeyTyped(evt);
            }
        });
        getContentPane().add(txt_no_hp_ortu);
        txt_no_hp_ortu.setBounds(1130, 140, 150, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Data Orang Tua/Wali");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 290, 128, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pekerjaan Orang Tua/Wali");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(70, 320, 142, 15);

        txt_kerja_ortu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kerja_ortuKeyTyped(evt);
            }
        });
        getContentPane().add(txt_kerja_ortu);
        txt_kerja_ortu.setBounds(230, 310, 180, 30);

        btn_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_keluar.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Close 33x30.png")); // NOI18N
        btn_keluar.setToolTipText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_keluar);
        btn_keluar.setBounds(980, 400, 60, 60);

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Edit 33x30.png")); // NOI18N
        btn_edit.setToolTipText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(800, 400, 60, 60);

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\delete 33x30.png")); // NOI18N
        btn_hapus.setToolTipText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(890, 400, 60, 60);

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\save 33x30.png")); // NOI18N
        btn_simpan.setToolTipText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(710, 400, 60, 60);

        btn_baru.setBackground(new java.awt.Color(255, 255, 255));
        btn_baru.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Add 33x30.png")); // NOI18N
        btn_baru.setToolTipText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        getContentPane().add(btn_baru);
        btn_baru.setBounds(620, 400, 60, 60);

        tabellist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 480, 1370, 290);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Penghasilan Rata - Rata");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 360, 127, 15);

        txt_hasil_rata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hasil_rataKeyTyped(evt);
            }
        });
        getContentPane().add(txt_hasil_rata);
        txt_hasil_rata.setBounds(230, 350, 180, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jumlah Tanggungan");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(70, 400, 110, 15);

        txt_jumlah_tanggungan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlah_tanggunganKeyTyped(evt);
            }
        });
        getContentPane().add(txt_jumlah_tanggungan);
        txt_jumlah_tanggungan.setBounds(230, 390, 180, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("No Hp");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(70, 440, 34, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama Lengkap Bank");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(970, 190, 110, 15);

        txt_namabank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namabankKeyTyped(evt);
            }
        });
        getContentPane().add(txt_namabank);
        txt_namabank.setBounds(1100, 180, 180, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("No Rekening");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(970, 230, 80, 20);

        txt_norek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_norekKeyTyped(evt);
            }
        });
        getContentPane().add(txt_norek);
        txt_norek.setBounds(1100, 220, 180, 30);

        jLabel1.setText("+62");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1100, 150, 30, 14);

        txt_no_hp_mhs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_hp_mhsKeyTyped(evt);
            }
        });
        getContentPane().add(txt_no_hp_mhs);
        txt_no_hp_mhs.setBounds(260, 430, 150, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Status");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(970, 270, 80, 20);

        txt_status.setEditable(false);
        txt_status.setEnabled(false);
        txt_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_statusKeyTyped(evt);
            }
        });
        getContentPane().add(txt_status);
        txt_status.setBounds(1100, 260, 180, 30);

        jLabel24.setText("+62");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(230, 440, 30, 20);

        jLabel25.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\BG-1366x768.jpg")); // NOI18N
        jLabel25.setToolTipText(""); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, -6, 1370, 780);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jkActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (txt_nim.getText()==""||
                txt_nama.getText()==""||
                cmb_jk.getSelectedIndex()==0||
                txt_almt.getText()==""||
                txt_nama_pt.getText()==""||
                txt_prodi.getText()==""||
                txt_semester.getText()==""||
                txt_angkatan.getText()==""||
                txt_ipk.getText()==""||
                txt_prestasi.getText()==""||
                txt_no_hp_mhs.getText()==""||
                txt_kerja_ortu.getText()==""||
                txt_hasil_rata.getText()==""||
                txt_jumlah_tanggungan.getText()==""||
                txt_no_hp_ortu.getText()==""||
                txt_namabank.getText()==""||
                txt_norek.getText()=="") 
        {
            JOptionPane.showMessageDialog(null, "Data anda Belum Lengkap");
        } else {
            
        
        Kelas.inputdata idm = new Kelas.inputdata();
        idm.nim=txt_nim.getText();
        idm.nama=txt_nama.getText();
        idm.jk_mhs=(String) cmb_jk.getSelectedItem();
        idm.almt_rmh=txt_almt.getText();
        idm.perguruan_tinggi=txt_nama_pt.getText();
        idm.prodi=txt_prodi.getText();
        idm.semester=txt_semester.getText();
        idm.angkatan=txt_angkatan.getText();
        idm.ipk=txt_ipk.getText();
        idm.prestasi=txt_prestasi.getText();
        idm.no_hp_mhs=txt_no_hp_mhs.getText();
        idm.pekerjaan_ortu=txt_kerja_ortu.getText();
        idm.penghasilan_rata=txt_hasil_rata.getText();
        idm.jumlah_tanggungan=txt_jumlah_tanggungan.getText();
        idm.no_hp_ortu=txt_no_hp_ortu.getText();
        idm.nama_lkp_bank=txt_namabank.getText();
        idm.no_rek=txt_norek.getText();
        idm.status=txt_status.getText();
        
        try{
            idm.simpan();
            bersih();
            tombol(false);
            JOptionPane.showMessageDialog(null, "Data anda Berhasil disimpan");
            
        }catch (Exception e){
            bersih();
            tombol(false);
            JOptionPane.showMessageDialog(null, "Maaf anda sudah terdaftar");
        }viewdata();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        String objButton[]={"yes","no"};
        int PromptResult = JOptionPane.showOptionDialog(null, "Apakah anda ingin menghapus data ini..?","Message",
                JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE, null, objButton, objButton[1]);
        if(PromptResult==0){
           Kelas.inputdata idm = new Kelas.inputdata();
           idm.nim=txt_nim.getText();
           try{
                idm.hapus();
                JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                bersih();
                viewdata();
                tombol(false);
                btn_simpan.setEnabled(true);
            }
           catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        Kelas.inputdata idm = new Kelas.inputdata();
        idm.nim=txt_nim.getText();
        idm.nama=txt_nama.getText();
        idm.jk_mhs=(String) cmb_jk.getSelectedItem();
        idm.almt_rmh=txt_almt.getText();
        idm.perguruan_tinggi=txt_nama_pt.getText();
        idm.prodi=txt_prodi.getText();
        idm.semester=txt_semester.getText();
        idm.angkatan=txt_angkatan.getText();
        idm.ipk=txt_ipk.getText();
        idm.prestasi=txt_prestasi.getText();
        idm.no_hp_mhs=txt_no_hp_mhs.getText();
        idm.pekerjaan_ortu=txt_kerja_ortu.getText();
        idm.penghasilan_rata=txt_hasil_rata.getText();
        idm.jumlah_tanggungan=txt_jumlah_tanggungan.getText();
        idm.no_hp_ortu=txt_no_hp_ortu.getText();
        idm.nama_lkp_bank=txt_namabank.getText();
        idm.no_rek=txt_norek.getText();
        idm.status=txt_status.getText();
        
        try{
            idm.edit();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            bersih();
            viewdata();
            
            tombol(false);
            btn_simpan.setEnabled(true);
            
        }catch (Exception e){
            
            JOptionPane.showMessageDialog(null, "Data ini sudah ada");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabellistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellistMouseClicked
        // TODO add your handling code here:
        tombol(true);
        btn_simpan.setEnabled(false);
        
        int row = tabellist.getSelectedRow();
        txt_nim.setText(tabellist.getModel().getValueAt(row,0 ).toString());
        txt_nama.setText(tabellist.getModel().getValueAt(row,1 ).toString());
        cmb_jk.setSelectedItem(tabellist.getModel().getValueAt(row,2).toString());
        txt_almt.setText(tabellist.getModel().getValueAt(row,3 ).toString());
        txt_nama_pt.setText(tabellist.getModel().getValueAt(row,4 ).toString());
        txt_prodi.setText(tabellist.getModel().getValueAt(row,5 ).toString());
        txt_semester.setText(tabellist.getModel().getValueAt(row,6 ).toString());
        txt_angkatan.setText(tabellist.getModel().getValueAt(row,7 ).toString());
        txt_ipk.setText(tabellist.getModel().getValueAt(row,8 ).toString());
        txt_prestasi.setText(tabellist.getModel().getValueAt(row,9 ).toString());
        txt_no_hp_mhs.setText(tabellist.getModel().getValueAt(row,10 ).toString());
        txt_kerja_ortu.setText(tabellist.getModel().getValueAt(row,11 ).toString());
        txt_hasil_rata.setText(tabellist.getModel().getValueAt(row,12 ).toString());
        txt_jumlah_tanggungan.setText(tabellist.getModel().getValueAt(row,13 ).toString());
        txt_no_hp_ortu.setText(tabellist.getModel().getValueAt(row,14 ).toString());
        txt_namabank.setText(tabellist.getModel().getValueAt(row,15 ).toString());
        txt_norek.setText(tabellist.getModel().getValueAt(row,16 ).toString());
        txt_status.setText(tabellist.getModel().getValueAt(row,17 ).toString());
        
    }//GEN-LAST:event_tabellistMouseClicked

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        bersih();
        txt_nim.requestFocus();
        tombol(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_btn_baruActionPerformed

    private void txt_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nimActionPerformed

    private void txt_nimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nimKeyTyped
        // TODO add your handling code here:
        if(txt_nim.getText().length()>9)
        {
        JOptionPane.showMessageDialog(null,"Maaf NPM Anda Terlalu Panjang");
        evt.consume();      
        }
    }//GEN-LAST:event_txt_nimKeyTyped

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_nama.getText().length()>29)
        {
        JOptionPane.showMessageDialog(null,"Maaf Nama Anda Terlalu Panjang");
        evt.consume();      
        }
    }//GEN-LAST:event_txt_namaKeyTyped

    private void txt_almtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_almtKeyTyped
        // TODO add your handling code here:
        if(txt_almt.getText().length()>49)
        {
        JOptionPane.showMessageDialog(null,"Maaf Alamat Anda Terlalu Panjang");
        evt.consume();      
        }
    }//GEN-LAST:event_txt_almtKeyTyped

    private void txt_kerja_ortuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kerja_ortuKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_kerja_ortu.getText().length()>24)
        {
        JOptionPane.showMessageDialog(null,"Maaf Nama Pekejaan Anda Terlalu Panjang");
        evt.consume();      
        }
    }//GEN-LAST:event_txt_kerja_ortuKeyTyped

    private void txt_hasil_rataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hasil_rataKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_hasil_rata.getText().length()>10)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nilai Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_hasil_rataKeyTyped

    private void txt_jumlah_tanggunganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlah_tanggunganKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_jumlah_tanggungan.getText().length()>10)
        {
            JOptionPane.showMessageDialog(null,"Maaf Jumlah Tangungan Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_jumlah_tanggunganKeyTyped

    private void txt_no_hp_mhsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_hp_mhsKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_no_hp_mhs.getText().length()>14)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nomor HP Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_no_hp_mhsKeyTyped

    private void txt_nama_ptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_ptKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_nama_pt.getText().length()>50)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nama Perguruan Tinggi Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_nama_ptKeyTyped

    private void txt_prodiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prodiKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_hasil_rata.getText().length()>50)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nama Prodi Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_prodiKeyTyped

    private void txt_semesterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_semesterKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_semester.getText().length()>2)
        {
            JOptionPane.showMessageDialog(null,"Maaf Semester Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_semesterKeyTyped

    private void txt_angkatanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_angkatanKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_angkatan.getText().length()>4)
        {
            JOptionPane.showMessageDialog(null,"Maaf Angkatan Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_angkatanKeyTyped

    private void txt_ipkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ipkKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_ipk.getText().length()>4)
        {
            JOptionPane.showMessageDialog(null,"Maaf IPK Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_ipkKeyTyped

    private void txt_prestasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prestasiKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_prestasi.getText().length()>59)
        {
            JOptionPane.showMessageDialog(null,"Maaf Prestasi Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_prestasiKeyTyped

    private void txt_no_hp_ortuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_hp_ortuKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_no_hp_ortu.getText().length()>14)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nomor HP Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_no_hp_ortuKeyTyped

    private void txt_namabankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namabankKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
        if(txt_namabank.getText().length()>29)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nama Bank Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_namabankKeyTyped

    private void txt_norekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_norekKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
        if(txt_norek.getText().length()>30)
        {
            JOptionPane.showMessageDialog(null,"Maaf Nomor Rekening Anda Terlalu Panjang");
            evt.consume();      
        }
    }//GEN-LAST:event_txt_norekKeyTyped

    private void txt_statusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_statusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusKeyTyped

    private void txt_nama_ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_ptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_ptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FData_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FData_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FData_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FData_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FData_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox cmb_jk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabellist;
    private javax.swing.JTextField txt_almt;
    private javax.swing.JTextField txt_angkatan;
    private javax.swing.JTextField txt_hasil_rata;
    private javax.swing.JTextField txt_ipk;
    private javax.swing.JTextField txt_jumlah_tanggungan;
    private javax.swing.JTextField txt_kerja_ortu;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_pt;
    private javax.swing.JTextField txt_namabank;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_no_hp_mhs;
    private javax.swing.JTextField txt_no_hp_ortu;
    private javax.swing.JTextField txt_norek;
    private javax.swing.JTextField txt_prestasi;
    private javax.swing.JTextField txt_prodi;
    private javax.swing.JTextField txt_semester;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
