/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beasiswa;

/**
 *
 * @author RRQ'Toothless
 */
public class FMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FMenuUtama
     */
    public FMenuUtama() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_data_mhs1 = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_hasil = new javax.swing.JButton();
        btn_about = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu5.setText("jMenu5");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Beasiswa");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 90, 110, 29);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Pendaftaran");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 70, 90, 17);

        btn_data_mhs1.setBackground(new java.awt.Color(255, 255, 255));
        btn_data_mhs1.setForeground(new java.awt.Color(255, 255, 255));
        btn_data_mhs1.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Menu 128.png")); // NOI18N
        btn_data_mhs1.setToolTipText("Data Mahasiswa");
        btn_data_mhs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_mhs1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data_mhs1);
        btn_data_mhs1.setBounds(300, 210, 160, 140);

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Close 128.png")); // NOI18N
        btn_exit.setToolTipText("Keluar");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(680, 210, 150, 137);

        btn_hasil.setBackground(new java.awt.Color(255, 255, 255));
        btn_hasil.setForeground(new java.awt.Color(255, 255, 255));
        btn_hasil.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\hasil 128x128.png")); // NOI18N
        btn_hasil.setToolTipText("Hasil Seleksi");
        btn_hasil.setBorder(null);
        btn_hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hasilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hasil);
        btn_hasil.setBounds(110, 210, 160, 140);

        btn_about.setBackground(new java.awt.Color(255, 255, 255));
        btn_about.setForeground(new java.awt.Color(255, 255, 255));
        btn_about.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\About 128.png")); // NOI18N
        btn_about.setToolTipText("About Programmer");
        btn_about.setBorder(null);
        btn_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_about);
        btn_about.setBounds(490, 210, 160, 140);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("www.itera.ac.id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 450, 100, 20);

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSTITUT TEKNOLOGI SUMATRA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 430, 340, 20);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 460, 0, 40);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 425, 0, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 390, 0, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Logo-128.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(800, 20, 130, 140);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("V 1.0");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(910, 490, 25, 14);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(898, 460, 0, 0);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Copyright© adelia_yasmin");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(810, 470, 120, 14);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, -10, 950, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\BG-1366x768.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 174, 138), 5));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 950, 510);

        setSize(new java.awt.Dimension(950, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hasilActionPerformed
        // TODO add your handling code here:
        new FHasil().setVisible(true);
    }//GEN-LAST:event_btn_hasilActionPerformed

    private void btn_data_mhs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_mhs1ActionPerformed
        // TODO add your handling code here:
        new FData_Mahasiswa().setVisible(true);
    }//GEN-LAST:event_btn_data_mhs1ActionPerformed

    private void btn_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutActionPerformed
        // TODO add your handling code here:
        new Fabout().setVisible(true);
    }//GEN-LAST:event_btn_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_about;
    private javax.swing.JButton btn_data_mhs1;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_hasil;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu5;
    // End of variables declaration//GEN-END:variables
}
