/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beasiswa;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Kelas.koneksi;
import net.proteanit.sql.DbUtils;
import java.awt.FlowLayout;
/**
 *
 * @author RRQ'Toothless
 */
public class FTimSeleksi extends javax.swing.JFrame {
    ResultSet resultset;
    Statement statement;
    /**
     * Creates new form FTimSeleksi
     */
    public FTimSeleksi() {
        initComponents();
        tombol(false);
        btn_hapus.setEnabled(false);
        btn_baru.setEnabled(false);
        btn_simpan.setEnabled(false);
        bersih();
        viewdata(); 
    }
    public void viewdata(){
        Kelas.inputdata idn = new Kelas.inputdata();
        try{
            tabellist.setModel(DbUtils.resultSetToTableModel(idn.Updatelisttable()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    void bersih(){
            txt_nim.setText("");
            txt_nama.setText("");
            cmb_jk.setSelectedIndex(0);
            txt_almt.setText("");
            txt_nama_pt.setText("");
            txt_prodi.setText("");
            txt_semester.setText("");
            txt_angkatan.setText("");
            txt_ipk.setText("");
            txt_prestasi.setText("");
            txt_no_hp_mhs.setText("");
            txt_kerja_ortu.setText("");
            txt_hasil_rata.setText("");
            txt_jumlah_tanggungan.setText("");
            txt_no_hp_ortu.setText("");
            txt_namabank.setText("");
            txt_norek.setText("");
            txt_status.setText("");
    }
    void tombol(boolean status){
        btn_edit.setEnabled(status);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_namabank = new javax.swing.JTextField();
        btn_baru = new javax.swing.JButton();
        txt_prodi = new javax.swing.JTextField();
        txt_angkatan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_norek = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_prestasi = new javax.swing.JTextField();
        txt_no_hp_mhs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_hasil_rata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_nama_pt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_jk = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_ipk = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        txt_semester = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_no_hp_ortu = new javax.swing.JTextField();
        txt_almt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_jumlah_tanggungan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_kerja_ortu = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellist = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Team Seleksi");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("No Rekening");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jumlah Tanggungan");

        txt_namabank.setEditable(false);
        txt_namabank.setEnabled(false);
        txt_namabank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namabankKeyTyped(evt);
            }
        });

        btn_baru.setBackground(new java.awt.Color(255, 255, 255));
        btn_baru.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Add 33x30.png")); // NOI18N
        btn_baru.setToolTipText("Baru");
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });

        txt_prodi.setEditable(false);
        txt_prodi.setEnabled(false);
        txt_prodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prodiKeyTyped(evt);
            }
        });

        txt_angkatan.setEditable(false);
        txt_angkatan.setEnabled(false);
        txt_angkatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_angkatanKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");

        txt_norek.setEditable(false);
        txt_norek.setEnabled(false);
        txt_norek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_norekKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Prestasi");

        txt_prestasi.setEditable(false);
        txt_prestasi.setEnabled(false);
        txt_prestasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prestasiKeyTyped(evt);
            }
        });

        txt_no_hp_mhs.setEditable(false);
        txt_no_hp_mhs.setEnabled(false);
        txt_no_hp_mhs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_hp_mhsKeyTyped(evt);
            }
        });

        jLabel1.setText("+62");

        btn_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_keluar.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Close 33x30.png")); // NOI18N
        btn_keluar.setToolTipText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pekerjaan Orang Tua/Wali");

        txt_hasil_rata.setEditable(false);
        txt_hasil_rata.setEnabled(false);
        txt_hasil_rata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hasil_rataKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");

        txt_nama.setEditable(false);
        txt_nama.setEnabled(false);
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });

        txt_nama_pt.setEditable(false);
        txt_nama_pt.setEnabled(false);
        txt_nama_pt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nama_ptKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Program Studi");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IPK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");

        cmb_jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Jenis Kelamin --", "PRIA", "WANITA" }));
        cmb_jk.setEnabled(false);
        cmb_jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jkActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("No HP");

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\delete 33x30.png")); // NOI18N
        btn_hapus.setToolTipText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("No Hp");

        txt_ipk.setEditable(false);
        txt_ipk.setEnabled(false);
        txt_ipk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ipkKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nama Lengkap Bank");

        txt_nim.setEditable(false);
        txt_nim.setEnabled(false);
        txt_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nimActionPerformed(evt);
            }
        });
        txt_nim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nimKeyTyped(evt);
            }
        });

        txt_semester.setEditable(false);
        txt_semester.setEnabled(false);
        txt_semester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_semesterKeyTyped(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\save 33x30.png")); // NOI18N
        btn_simpan.setToolTipText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Angkatan");

        jLabel24.setText("+62");

        txt_no_hp_ortu.setEditable(false);
        txt_no_hp_ortu.setEnabled(false);
        txt_no_hp_ortu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_hp_ortuKeyTyped(evt);
            }
        });

        txt_almt.setEditable(false);
        txt_almt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_almt.setEnabled(false);
        txt_almt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_almtKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Mahasiswa");

        txt_jumlah_tanggungan.setEditable(false);
        txt_jumlah_tanggungan.setEnabled(false);
        txt_jumlah_tanggungan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlah_tanggunganKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Perguruan Tinggi");

        txt_kerja_ortu.setEditable(false);
        txt_kerja_ortu.setEnabled(false);
        txt_kerja_ortu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kerja_ortuKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Status");

        txt_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_statusKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Data Orang Tua/Wali");

        btn_edit.setBackground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\Edit 33x30.png")); // NOI18N
        btn_edit.setToolTipText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        tabellist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabellist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellist);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Penghasilan Rata - Rata");

        jLabel25.setIcon(new javax.swing.ImageIcon("D:\\KAMPUS\\Java\\P_Beasiswa\\P_Beasiswa\\Icon\\BG-1366x768.jpg")); // NOI18N
        jLabel25.setToolTipText(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel26))
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(136, 136, 136)
                .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(txt_nama_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(txt_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(130, 130, 130)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel8)
                .addGap(63, 63, 63)
                .addComponent(txt_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel15)
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_no_hp_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(89, 89, 89)
                .addComponent(cmb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(88, 88, 88)
                .addComponent(txt_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel17)
                .addGap(20, 20, 20)
                .addComponent(txt_namabank, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addGap(123, 123, 123)
                .addComponent(txt_almt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel12)
                .addGap(88, 88, 88)
                .addComponent(txt_angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txt_norek, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel16)
                .addGap(362, 362, 362)
                .addComponent(jLabel13)
                .addGap(122, 122, 122)
                .addComponent(txt_ipk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(txt_kerja_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel20)
                .addGap(33, 33, 33)
                .addComponent(txt_hasil_rata, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel21)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_jumlah_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt_no_hp_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(210, 210, 210)
                .addComponent(btn_baru)
                .addGap(25, 25, 25)
                .addComponent(btn_simpan)
                .addGap(25, 25, 25)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_keluar))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel22))
            .addGroup(layout.createSequentialGroup()
                .addGap(970, 970, 970)
                .addComponent(jLabel14))
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel26))
                    .addComponent(jLabel18))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_hp_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_semester, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namabank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_almt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_angkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_norek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addComponent(txt_ipk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addComponent(txt_kerja_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addComponent(txt_hasil_rata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_jumlah_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_no_hp_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(btn_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel22))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel14))
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namabankKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namabankKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namabankKeyTyped

    private void txt_prodiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prodiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prodiKeyTyped

    private void txt_angkatanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_angkatanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_angkatanKeyTyped

    private void txt_norekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_norekKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_norekKeyTyped

    private void txt_prestasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prestasiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prestasiKeyTyped

    private void txt_no_hp_mhsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_hp_mhsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_hp_mhsKeyTyped

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_hasil_rataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hasil_rataKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hasil_rataKeyTyped

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaKeyTyped

    private void txt_nama_ptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_ptKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_ptKeyTyped

    private void cmb_jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_jkActionPerformed

    private void txt_ipkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ipkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ipkKeyTyped

    private void txt_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nimActionPerformed

    private void txt_nimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nimKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nimKeyTyped

    private void txt_semesterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_semesterKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_semesterKeyTyped

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_no_hp_ortuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_hp_ortuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_hp_ortuKeyTyped

    private void txt_almtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_almtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_almtKeyTyped

    private void txt_jumlah_tanggunganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlah_tanggunganKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlah_tanggunganKeyTyped

    private void txt_kerja_ortuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kerja_ortuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kerja_ortuKeyTyped

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        Kelas.inputdata idm = new Kelas.inputdata();
        idm.nim=txt_nim.getText();
        idm.nama=txt_nama.getText();
        idm.jk_mhs=(String) cmb_jk.getSelectedItem();
        idm.almt_rmh=txt_almt.getText();
        idm.perguruan_tinggi=txt_nama_pt.getText();
        idm.prodi=txt_prodi.getText();
        idm.semester=txt_semester.getText();
        idm.angkatan=txt_angkatan.getText();
        idm.ipk=txt_ipk.getText();
        idm.prestasi=txt_prestasi.getText();
        idm.no_hp_mhs=txt_no_hp_mhs.getText();
        idm.pekerjaan_ortu=txt_kerja_ortu.getText();
        idm.penghasilan_rata=txt_hasil_rata.getText();
        idm.jumlah_tanggungan=txt_jumlah_tanggungan.getText();
        idm.no_hp_ortu=txt_no_hp_ortu.getText();
        idm.nama_lkp_bank=txt_namabank.getText();
        idm.no_rek=txt_norek.getText();
        idm.status=txt_status.getText();

        try{
            idm.edit();
            JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
            bersih();
            viewdata();
            tombol(false);

        }catch (Exception e){

            JOptionPane.showMessageDialog(null, "Data ini sudah ada");
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabellistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellistMouseClicked
        // TODO add your handling code here:
        tombol(true);

        int row = tabellist.getSelectedRow();
        txt_nim.setText(tabellist.getModel().getValueAt(row,0 ).toString());
        txt_nama.setText(tabellist.getModel().getValueAt(row,1 ).toString());
        cmb_jk.setSelectedItem(tabellist.getModel().getValueAt(row,2).toString());
        txt_almt.setText(tabellist.getModel().getValueAt(row,3 ).toString());
        txt_nama_pt.setText(tabellist.getModel().getValueAt(row,4 ).toString());
        txt_prodi.setText(tabellist.getModel().getValueAt(row,5 ).toString());
        txt_semester.setText(tabellist.getModel().getValueAt(row,6 ).toString());
        txt_angkatan.setText(tabellist.getModel().getValueAt(row,7 ).toString());
        txt_ipk.setText(tabellist.getModel().getValueAt(row,8 ).toString());
        txt_prestasi.setText(tabellist.getModel().getValueAt(row,9 ).toString());
        txt_no_hp_mhs.setText(tabellist.getModel().getValueAt(row,10 ).toString());
        txt_kerja_ortu.setText(tabellist.getModel().getValueAt(row,11 ).toString());
        txt_hasil_rata.setText(tabellist.getModel().getValueAt(row,12 ).toString());
        txt_jumlah_tanggungan.setText(tabellist.getModel().getValueAt(row,13 ).toString());
        txt_no_hp_ortu.setText(tabellist.getModel().getValueAt(row,14 ).toString());
        txt_namabank.setText(tabellist.getModel().getValueAt(row,15 ).toString());
        txt_norek.setText(tabellist.getModel().getValueAt(row,16 ).toString());
        txt_status.setText(tabellist.getModel().getValueAt(row,17 ).toString());

    }//GEN-LAST:event_tabellistMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_baruActionPerformed

    private void txt_statusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_statusKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_statusKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTimSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTimSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTimSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTimSeleksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTimSeleksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox cmb_jk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabellist;
    private javax.swing.JTextField txt_almt;
    private javax.swing.JTextField txt_angkatan;
    private javax.swing.JTextField txt_hasil_rata;
    private javax.swing.JTextField txt_ipk;
    private javax.swing.JTextField txt_jumlah_tanggungan;
    private javax.swing.JTextField txt_kerja_ortu;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama_pt;
    private javax.swing.JTextField txt_namabank;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_no_hp_mhs;
    private javax.swing.JTextField txt_no_hp_ortu;
    private javax.swing.JTextField txt_norek;
    private javax.swing.JTextField txt_prestasi;
    private javax.swing.JTextField txt_prodi;
    private javax.swing.JTextField txt_semester;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
